on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  create-install-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12.1
      - run: pip install poetry
      - run: poetry install --only main
      - run: make generate-install-scripts
      - uses: actions/upload-artifact@v4
        with:
          name: install-scripts
          path: dist/

  install-amd64:
    runs-on: ubuntu-latest
    needs:
      - create-install-scripts
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: install-scripts
          path: dist/
      - run: sh dist/amd64.sh
      - uses: actions/upload-artifact@v4
        with:
          name: layers-amd64
          path: layers/

  install-arm64:
    runs-on: ubuntu-latest
    needs:
      - create-install-scripts
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64
      - uses: actions/download-artifact@v4
        with:
          name: install-scripts
          path: dist/
      - run: sh dist/arm64.sh
      - uses: actions/upload-artifact@v4
        with:
          name: layers-arm64
          path: layers/

  cdk-synth:
    runs-on: ubuntu-latest
    needs:
      - install-amd64
      - install-arm64
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: layers-amd64
          path: layers/
      - uses: actions/download-artifact@v4
        with:
          name: layers-arm64
          path: layers/
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12.1
      - uses: actions/setup-node@v4
        with:
          node-version: 20.12.1
      - run: pip install poetry
      - run: poetry install --only main
      - run: npm install
      - run: poetry run npx cdk synth
      - uses: actions/upload-artifact@v4
        with:
          name: cdk.out
          path: cdk.out/

  cdk-deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        aws_region:
          - af-south-1
          - ap-east-1
          - ap-northeast-1
          - ap-northeast-2
          - ap-northeast-3
          - ap-south-1
          - ap-south-2
          - ap-southeast-1
          - ap-southeast-2
          - ap-southeast-3
          - ap-southeast-4
          - ca-central-1
          - ca-west-1
          - eu-central-1
          - eu-central-2
          - eu-north-1
          - eu-south-1
          - eu-south-2
          - eu-west-1
          - eu-west-2
          - eu-west-3
          - il-central-1
          - me-central-1
          - me-south-1
          - sa-east-1
          - us-east-1
          - us-east-2
          - us-west-1
          - us-west-2
    needs:
      - cdk-synth
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: layers-amd64
          path: layers/
      - uses: actions/download-artifact@v4
        with:
          name: layers-arm64
          path: layers/
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12.1
      - uses: actions/setup-node@v4
        with:
          node-version: 20.12.1
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ matrix.aws_region }}
      - run: pip install poetry
      - run: poetry install --only main
      - run: npm install
      - run: poetry run npx cdk deploy  --require-approval never


