import public_layers.utils.models.models as index
import pytest


class TestModuleConvert:
    @pytest.mark.parametrize(
        "module, expected",
        [
            (
                index.Module(
                    name="tmp",
                    layer_name="Tmp",
                    version="0.1.1",
                    is_individual_runtimes=False,
                    is_individual_architectures=False,
                ),
                [
                    index.BuildOptions(
                        name="LuciferousPublicLayers-Tmp",
                        arch="amd64",
                        runtime_version="3.12",
                        module="tmp==0.1.1",
                        logical_id="LuciferousPublicLayersTmp",
                    )
                ],
            ),
            (
                index.Module(
                    name="tmp",
                    layer_name="Tmp",
                    version="0.1.1",
                    extras=["aaa"],
                    is_individual_runtimes=False,
                    is_individual_architectures=False,
                ),
                [
                    index.BuildOptions(
                        name="LuciferousPublicLayers-Tmp",
                        arch="amd64",
                        runtime_version="3.12",
                        module="tmp[aaa]==0.1.1",
                        logical_id="LuciferousPublicLayersTmp",
                    ),
                ],
            ),
            (
                index.Module(
                    name="tmp",
                    layer_name="Tmp",
                    version="0.1.1",
                    extras=["aaa", "ccc", "bbb"],
                    is_individual_runtimes=False,
                    is_individual_architectures=False,
                ),
                [
                    index.BuildOptions(
                        name="LuciferousPublicLayers-Tmp",
                        arch="amd64",
                        runtime_version="3.12",
                        module="tmp[aaa,ccc,bbb]==0.1.1",
                        logical_id="LuciferousPublicLayersTmp",
                    ),
                ],
            ),
            (
                index.Module(
                    name="tmp",
                    layer_name="Tmp",
                    version="0.1.1",
                    is_individual_runtimes=True,
                    is_individual_architectures=False,
                ),
                [
                    index.BuildOptions(
                        name="LuciferousPublicLayers-Tmp-Python3.12",
                        arch="amd64",
                        runtime_version="3.12",
                        module="tmp==0.1.1",
                        logical_id="LuciferousPublicLayersTmpPython312",
                    ),
                    index.BuildOptions(
                        name="LuciferousPublicLayers-Tmp-Python3.11",
                        arch="amd64",
                        runtime_version="3.11",
                        module="tmp==0.1.1",
                        logical_id="LuciferousPublicLayersTmpPython311",
                    ),
                    index.BuildOptions(
                        name="LuciferousPublicLayers-Tmp-Python3.10",
                        arch="amd64",
                        runtime_version="3.10",
                        module="tmp==0.1.1",
                        logical_id="LuciferousPublicLayersTmpPython310",
                    ),
                    index.BuildOptions(
                        name="LuciferousPublicLayers-Tmp-Python3.9",
                        arch="amd64",
                        runtime_version="3.9",
                        module="tmp==0.1.1",
                        logical_id="LuciferousPublicLayersTmpPython39",
                    ),
                ],
            ),
            (
                index.Module(
                    name="tmp",
                    layer_name="Tmp",
                    version="0.1.1",
                    is_individual_runtimes=False,
                    is_individual_architectures=True,
                ),
                [
                    index.BuildOptions(
                        name="LuciferousPublicLayers-Tmp-X86_64",
                        arch="amd64",
                        runtime_version="3.12",
                        module="tmp==0.1.1",
                        logical_id="LuciferousPublicLayersTmpX8664",
                    ),
                    index.BuildOptions(
                        name="LuciferousPublicLayers-Tmp-Arm64",
                        arch="arm64",
                        runtime_version="3.12",
                        module="tmp==0.1.1",
                        logical_id="LuciferousPublicLayersTmpArm64",
                    ),
                ],
            ),
            (
                index.Module(
                    name="tmp",
                    layer_name="Tmp",
                    version="0.1.1",
                    is_individual_runtimes=True,
                    is_individual_architectures=True,
                ),
                [
                    index.BuildOptions(
                        name="LuciferousPublicLayers-Tmp-Python3.12-X86_64",
                        arch="amd64",
                        runtime_version="3.12",
                        module="tmp==0.1.1",
                        logical_id="LuciferousPublicLayersTmpPython312X8664",
                    ),
                    index.BuildOptions(
                        name="LuciferousPublicLayers-Tmp-Python3.11-X86_64",
                        arch="amd64",
                        runtime_version="3.11",
                        module="tmp==0.1.1",
                        logical_id="LuciferousPublicLayersTmpPython311X8664",
                    ),
                    index.BuildOptions(
                        name="LuciferousPublicLayers-Tmp-Python3.10-X86_64",
                        arch="amd64",
                        runtime_version="3.10",
                        module="tmp==0.1.1",
                        logical_id="LuciferousPublicLayersTmpPython310X8664",
                    ),
                    index.BuildOptions(
                        name="LuciferousPublicLayers-Tmp-Python3.9-X86_64",
                        arch="amd64",
                        runtime_version="3.9",
                        module="tmp==0.1.1",
                        logical_id="LuciferousPublicLayersTmpPython39X8664",
                    ),
                    index.BuildOptions(
                        name="LuciferousPublicLayers-Tmp-Python3.12-Arm64",
                        arch="arm64",
                        runtime_version="3.12",
                        module="tmp==0.1.1",
                        logical_id="LuciferousPublicLayersTmpPython312Arm64",
                    ),
                    index.BuildOptions(
                        name="LuciferousPublicLayers-Tmp-Python3.11-Arm64",
                        arch="arm64",
                        runtime_version="3.11",
                        module="tmp==0.1.1",
                        logical_id="LuciferousPublicLayersTmpPython311Arm64",
                    ),
                    index.BuildOptions(
                        name="LuciferousPublicLayers-Tmp-Python3.10-Arm64",
                        arch="arm64",
                        runtime_version="3.10",
                        module="tmp==0.1.1",
                        logical_id="LuciferousPublicLayersTmpPython310Arm64",
                    ),
                    index.BuildOptions(
                        name="LuciferousPublicLayers-Tmp-Python3.9-Arm64",
                        arch="arm64",
                        runtime_version="3.9",
                        module="tmp==0.1.1",
                        logical_id="LuciferousPublicLayersTmpPython39Arm64",
                    ),
                ],
            ),
        ],
    )
    def test_normal(self, module, expected):
        actual = module.convert()
        assert set(actual) == set(expected)
